// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o7C61dL2AAD7uCRtgHRJ1p
// Component: DDHEaM0ZdLCe

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: o7C61dL2AAD7uCRtgHRJ1p/projectcss
import sty from "./PlasmicVariantKarte.module.css"; // plasmic-import: DDHEaM0ZdLCe/css

createPlasmicElementProxy;

export type PlasmicVariantKarte__VariantMembers = {
  selected: "selected";
  farbe: "farbe";
};
export type PlasmicVariantKarte__VariantsArgs = {
  selected?: SingleBooleanChoiceArg<"selected">;
  farbe?: SingleBooleanChoiceArg<"farbe">;
};
type VariantPropType = keyof PlasmicVariantKarte__VariantsArgs;
export const PlasmicVariantKarte__VariantProps = new Array<VariantPropType>(
  "selected",
  "farbe"
);

export type PlasmicVariantKarte__ArgsType = {
  onSelect?: () => void;
  value?: string;
};
type ArgPropType = keyof PlasmicVariantKarte__ArgsType;
export const PlasmicVariantKarte__ArgProps = new Array<ArgPropType>(
  "onSelect",
  "value"
);

export type PlasmicVariantKarte__OverridesType = {
  tab?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultVariantKarteProps {
  onSelect?: () => void;
  value?: string;
  selected?: SingleBooleanChoiceArg<"selected">;
  farbe?: SingleBooleanChoiceArg<"farbe">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVariantKarte__RenderFunc(props: {
  variants: PlasmicVariantKarte__VariantsArgs;
  args: PlasmicVariantKarte__ArgsType;
  overrides: PlasmicVariantKarte__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "selected",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.selected
      },
      {
        path: "farbe",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return (
                $props.variant.attributes[0].attribute.inputType === "SWATCH"
              );
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })() ?? $props.farbe
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"tab"}
      data-plasmic-override={overrides.tab}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.tab,
        {
          [sty.tabfarbe]: hasVariant($state, "farbe", "farbe"),
          [sty.tabselected]: hasVariant($state, "selected", "selected"),
          [sty.tabselected_farbe]:
            hasVariant($state, "farbe", "farbe") &&
            hasVariant($state, "selected", "selected")
        }
      )}
      onClick={async event => {
        const $steps = {};

        $steps["runUpdateVariant"] = true
          ? (() => {
              const actionArgs = { eventRef: $props["onSelect"] };
              return (({ eventRef, args }) => {
                return eventRef?.(...(args ?? []));
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["runUpdateVariant"] != null &&
          typeof $steps["runUpdateVariant"] === "object" &&
          typeof $steps["runUpdateVariant"].then === "function"
        ) {
          $steps["runUpdateVariant"] = await $steps["runUpdateVariant"];
        }
      }}
      style={
        hasVariant($state, "farbe", "farbe")
          ? (() => {
              try {
                return (() => {
                  return { backgroundColor: $props.value };
                })();
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return undefined;
                }
                throw e;
              }
            })()
          : undefined
      }
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text, {
          [sty.textfarbe]: hasVariant($state, "farbe", "farbe"),
          [sty.textselected]: hasVariant($state, "selected", "selected")
        })}
      >
        {"W:75 \u0445 H:82 cm"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  tab: ["tab", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  tab: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVariantKarte__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVariantKarte__VariantsArgs;
    args?: PlasmicVariantKarte__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVariantKarte__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVariantKarte__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVariantKarte__ArgProps,
          internalVariantPropNames: PlasmicVariantKarte__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVariantKarte__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "tab") {
    func.displayName = "PlasmicVariantKarte";
  } else {
    func.displayName = `PlasmicVariantKarte.${nodeName}`;
  }
  return func;
}

export const PlasmicVariantKarte = Object.assign(
  // Top-level PlasmicVariantKarte renders the root element
  makeNodeComponent("tab"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicVariantKarte
    internalVariantProps: PlasmicVariantKarte__VariantProps,
    internalArgProps: PlasmicVariantKarte__ArgProps
  }
);

export default PlasmicVariantKarte;
/* prettier-ignore-end */
